# CST3240 Touchscreen with ILI9341 Display
# This example shows a complete setup with touchscreen and display

esphome:
  name: cst3240-display

esp32:
  board: esp32dev

wifi:
  ssid: "YourWiFiNetwork"
  password: "YourWiFiPassword"

# Enable logging with touchscreen debug info
logger:
  level: DEBUG
  logs:
    cst3240.touchscreen: DEBUG

# Enable Home Assistant API
api:

# Enable OTA updates
ota:
  - platform: esphome

# External component configuration
external_components:
  - source: github://shyndman/personal-esphome-components
    components: [cst3240]

# I2C Bus for Touchscreen
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

# SPI Bus for Display
spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

# ILI9341 Display Configuration
display:
  - platform: ili9xxx
    id: my_display
    model: ILI9341
    dimensions: 320x240
    cs_pin: GPIO5
    dc_pin: GPIO2
    reset_pin: GPIO4
    transform:
      swap_xy: false
      mirror_x: false
      mirror_y: false
    auto_clear_enabled: false
    invert_colors: false

# CST3240 Touchscreen Configuration
touchscreen:
  - platform: cst3240
    id: my_touchscreen
    display: my_display
    interrupt_pin: GPIO15
    reset_pin: GPIO16
    calibration:
      x_min: 0
      x_max: 320
      y_min: 0
      y_max: 240
    transform:
      swap_xy: false
      mirror_x: false
      mirror_y: false

# Simple touch indicator
binary_sensor:
  - platform: touchscreen
    name: "Touch Detected"
    touchscreen_id: my_touchscreen
    x_min: 0
    x_max: 320
    y_min: 0
    y_max: 240