esphome:
  name: udp-audio-streamer-demo

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

wifi:
  ssid: "YOUR_WIFI_SSID"
  password: "YOUR_WIFI_PASSWORD"

logger:
api:
ota:
  - platform: esphome

external_components:
  - source: github://shyndman/personal-esphome-components
    components: [udp_audio_streamer]

i2s_audio:
  - id: i2s0
    i2s_lrclk_pin: GPIO42
    i2s_bclk_pin: GPIO41
    i2s_mclk_pin: GPIO40

microphone:
  - platform: i2s_audio
    id: i2s_mic
    adc_type: external
    i2s_audio_id: i2s0
    i2s_din_pin: GPIO2
    sample_rate: 16000

udp_audio_streamer:
  host: 192.168.1.50
  port: 7000
  chunk_duration: 40ms
  buffer_duration: 640ms
  microphone:
    microphone: i2s_mic
    bits_per_sample: 16
    channels: 0
